### ISSUE TITLE
Maintainers

### ISSUE THREAD

**Issue by mitchellwood** [conda-forge/dash-extensions-feedstock#2]
@thedirtyfew I have added a dash-extensions feedstock to conda-forge. Would you like to be added as a maintainer?

**Comment by whophil** [comment]
Hi @mitchellwood ! I've noticed that the maintenance of this recipe seems to have lapsed. I can help with this - are you able to add me as maintainer? Thanks!

**Comment by mitchellwood** [comment]
> Hi @mitchellwood ! I've noticed that the maintenance of this recipe seems to have lapsed. I can help with this - are you able to add me as maintainer? Thanks!

Hey @whophil, you should be added as a maintainer now

**Comment by whophil** [comment]
Thanks @mitchellwood !
